openapi: 3.0.0

info:
  title: ephemerEx
  version: "v1"
servers:
  - url: 'http://localhost:80'
    description: balancer


paths:
  /health:
    get:
      description: Возвращает статус здоровья приложения
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  instance_id:
                    type: string
          
  /new:
    post:
      description: Создает новое сообщение
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message_text:
                  type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                  error:
                    type: null
                  instance_id:
                    type: string
          
  /read:
    post:
      description: Возвращает текст сообщения по его идентификатору
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message_id:
                  type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_text:
                    type: string
                  error:
                    type: null
                  instance_id:
                    type: string